import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/contexts/auth-context";
import { AuthorizationProvider } from "@/lib/authz/AuthorizationProvider";
import { Toaster } from "@/components/ui/sonner";
import ApiErrorListener from "@/components/ApiErrorListener";
import { ThemeScript } from "@/components/navigation/ThemeScript";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                {/* Set initial theme before paint to avoid FOUC */}
                <ThemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthorizationProvider>
                    <AuthProvider>
                        <ApiErrorListener />
                        {children}
                    </AuthProvider>
                </AuthorizationProvider>
                <Toaster />
            </body>
        </html>
    );
}
