import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/contexts/auth-context";
import { AuthorizationProvider } from "@/lib/authz/AuthorizationProvider";
import { Toaster } from "@/components/ui/sonner";
import { useEffect } from "react";
import { onApiError } from "@/lib/api-events";
import { useAuthz } from "@/lib/authz/useAuthz";
import { toast } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Install a global API error listener to improve UX for 401/403
    function ApiErrorListener() {
        const { refresh } = useAuthz();
        useEffect(() => {
            const off = onApiError(async ({ status, message }) => {
                if (status === 401) {
                    toast.error(message || "Session expired. Please sign in.");
                } else if (status === 403) {
                    toast.error(message || "Not allowed.");
                    // Permissions may have changed; refresh in background
                    refresh().catch(() => {});
                }
            });
            return () => {
                off?.();
            };
        }, [refresh]);
        return null;
    }
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthProvider>
                    <AuthorizationProvider>
                        <ApiErrorListener />
                        {children}
                    </AuthorizationProvider>
                </AuthProvider>
                <Toaster />
            </body>
        </html>
    );
}
